import styles from '../styles/Home.module.css';
import Head from 'next/head';
import Link from 'next/link';
import AppLayout from '../components/AppLayout';

export default function Home() {
  return (
    <>
      <Head>
        <title>Devter</title>
        <meta name='description' content='Generated by create next app' />
        <link rel='icon' href='/favicon.ico' />
      </Head>
      <AppLayout>
        <h1 className={styles.title}>
          <a className={styles.enlace} href='https://nextjs.org'>
            devter
          </a>
        </h1>
        <nav className={styles.navigation}>
          <Link href='/timeline'>timeline</Link>
        </nav>
      </AppLayout>
    </>
  );
}
